spring.application.name=book-social-network
spring.datasource.url=jdbc:postgresql://localhost:5432/book_social_network
spring.datasource.username=postgres
spring.datasource.password=0000
spring.jpa.ddl-auto=update
spring.jpa.properties.hibernate.formate_sql=true
spring.jpa.database=postgresql
servlet.multipart.max-file-size=50MB
springdoc.default-produces-media-type=application/json
server.servlet.context-path=/api/v1/
spring.mail.host= localhost
spring.mail.port=1025
spring.mail.properties.mail.smtp.trust="*"
spring.mail.properties.mail.auth=true
spring.mail.properties.mail.starttls.enable=true
spring.mail.properties.mail.connectiontimeout=5000
spring.mail.properties.mail.timeout=3000
spring.mail.properties.mail.writetimeout=5000
application.security.jwt.secret-key=secretKey
application.security.jwt.expiration=8640000
application.mailing.frontend.activation-url=http//localhost:4200/activate-account

